export type VehicleArticlesResponseType = {
  vehicleId: number;
  productGroupId: number;
  countArticles: number;
  articles: ArticleType[];
};

export type ArticleType = {
  articleId: number;
  articleNo: string;
  supplierName: string;
  supplierId: number;
  articleProductName: string;
  productId: number;
  articleMediaType: number;
  articleMediaFileName: string;
  imageLink: string;
  imageMedia: string;
  s3ImageLink: string;
  s3image: string;
};

export type ArticleDetailsResponse = {
  articleNo: string;
    countArticles: number;
    articles: ArticleDetailType[];
  };
export type ArticleDetailsApiDbResponse = {
  db: (ArticleDB & { id: string })[] | null;
  api: {
    articleNo: string;
    countArticles: number;
    articles: ArticleDetailType[];
  }
  };

export type ArticleDetailType = {
  articleId: number;
  articleNo: string;
  articleProductName: string;
  supplierName: string;
  supplierId: number;
  articleMediaType: number;
  articleMediaFileName: string;
  articleInfo: ArticleInfoType;
  allSpecifications: null | {
    criteriaName: string;
    criteriaValue: never;
  }[];
  eanNo: {
    eanNumbers: string[] | null;
  };
  oemNo: OemNumberType[] | null;
  imageLink: string;
  imageMedia: string;
  s3ImageLink: string;
  s3image: string;
  compatibleCars: CompatibleCarType[];
};

export type ArticleInfoType = {
  articleId: number;
  articleNo: string;
  supplierId: number;
  supplierName: string;
  isAccessory: number;
  articleProductName: string;
};

export type OemNumberType = {
  oemBrand: string;
  oemDisplayNo: string;
};

export type CompatibleCarType = {
  vehicleId: number;
  modelId: number;
  manufacturerName: string;
  modelName: string;
  typeEngineName: string;
  constructionIntervalStart: string; // ISO date string
  constructionIntervalEnd: string | null; // can be null if ongoing
};

// Article properties b2b
export type ArticleDB = {
  ste?: number | null;
  iann?: number | null;
  cod?: string | null;
  libf?: string | null;
  uni?: string | null;
  nuni?: string | null;
  stk?: number | null;
  tva?: number | null;
  pac?: number | null;
  pacttc?: number | null;
  mar?: number | null;
  pvhtva?: number | null;
  pvttc?: number | null;
  prixgros?: number | null;
  frn?: string | null;
  nfrn?: string | null;
  fdc?: string | null;
  tfdc?: number | null;
  empl?: string | null;
  fam?: string | null;
  nfam?: string | null;
  ord?: number | null;
  pmp?: number | null;
  datstk?: Date | null;
  remfrn?: number | null;
  remcli?: number | null;
  tent?: number | null;
  tsrt?: number | null;
  dens?: number | null;
  prxdep?: number | null;
  dev?: string | null;
  stkmini?: number | null;
  uns?: string | null;
  denss?: number | null;
  codebar?: string | null;
  codefour?: string | null;
  prixpub?: number | null;
  prixsgros?: number | null;
  prixspec?: number | null;
  stock?: string | null;
  reffrn?: string | null;
  remacc?: string | null;
  sfam?: string | null;
  nsfam?: string | null;
  marm?: number | null;
  prxs?: number | null;
  qtes?: number | null;
  dernv?: number | null;
  equiv?: string | null;
  invent?: string | null;
  ngp?: string | null;
  numaut?: number | null;
  poids?: number | null;
  invent1?: string | null;
  corrig?: string | null;
  codimg?: string | null;
  prixpubttc?: number | null;
  marp?: number | null;
  exo?: string | null;
  ttcmaj?: number | null;
  flge?: string | null;
  prxm?: number | null;
  datc?: Date | null;
  datm?: Date | null;
  utlc?: string | null;
  nutlc?: string | null;
  utlm?: string | null;
  nutlm?: string | null;
  stkmag?: number | null;
  gerer?: string | null;
  minc?: number | null;
  empl1?: string | null;
  sfm?: number | null;
  plfrem?: number | null;
  blc?: string | null;
  fdcfrn?: number | null;
  pachtva?: number | null;
  prvttc?: number | null;
  txtzon?: string | null;
  cat?: string | null;
  ncat?: string | null;
  libcat?: string | null;
  stk1?: number | null;
  tentd?: number | null;
  tsrtd?: number | null;
  prxn?: string | null;
  prxach?: number | null;
  impc?: string | null;
  txtzon1?: string | null;
  txtzon2?: string | null;
  empl2?: string | null;
  b2b?: string | null;
  obs?: string | null;
  Oobsec?: string | null;
  coder?: string | null;
  pvhtvar?: number | null;
  mara?: number | null;
  nbrc?: number | null;
  marg?: number | null;
  coderr?: string | null;
  maj?: string | null;
  stkmax?: number | null;
  actif?: number | null;
  typ?: string | null;
  descrip?: string | null;
  ctrlach?: string | null;
};

export type Client = {
  ste?: number | null;
  iann?: number | null;
  codecli?: string | null;
  libcli?: string | null;
  adrcli?: string | null;
  telcli?: string | null;
  faxcli?: string | null;
  tvacli?: string | null;
  patcli?: string | null;
  prscli?: string | null;
  maicli?: string | null;
  adrclia?: string | null;
  adrclig?: string | null;
  timcli?: string | null;
  exocli?: string | null;
  plfcli?: number | null;
  debcli?: number | null;
  crecli?: number | null;
  typcli?: string | null;
  remcli?: number | null;
  devcli?: string | null;
  ndevcli?: string | null;
  ribcli?: string | null;
  autf?: string | null;
  accrem?: string | null;
  cptcli?: string | null;
  cmr?: string | null;
  ncmr?: string | null;
  rcv?: string | null;
  nrcv?: string | null;
  aut?: string | null;
  reg?: string | null;
  nreg?: string | null;
  typecli?: string | null;
  ntypecli?: string | null;
  encrcli?: number | null;
  impcli?: number | null;
  trvcli?: string | null;
  inscli?: string | null;
  vilcli?: string | null;
  regcli?: string | null;
  nvilcli?: string | null;
  nregcli?: string | null;
  marach?: number | null;
  bnkcli?: string | null;
  nbnkcli?: string | null;
  nbrfact?: number | null;
  codreg?: string | null;
  magcli?: string | null;
  nmagcli?: string | null;
  codefourn?: string | null;
  adrbnk?: string | null;
  clipass?: string | null;
  datc?: Date | null;
  datm?: Date | null;
  utlc?: string | null;
  nutlc?: string | null;
  utlm?: string | null;
  nutlm?: string | null;
  actv?: string | null;
  enccli?: number | null;
  badge?: string | null;
  numexo?: string | null;
  datexo?: Date | null;
  adm?: string | null;
  pswd?: string | null;
  remcaf?: string | null;
  remb2b?: number | null;
  numcnss?: number | null;
  clecnss?: number | null;
  nbrj?: number | null;
  delp?: number | null;
  paccli?: string | null;
  tauret?: number | null;
  modlp?: string | null;
  modp?: string | null;
  rib1?: string | null;
  bnk1?: string | null;
  nbnk1?: string | null;
  adr1?: string | null;
  rc?: string | null;
  impcc?: string | null;
  modep?: string | null;
  ctrlach?: string | null;
};
